# Generated by Django 3.1.5 on 2021-01-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=16, verbose_name='user_id')),
            ],
            options={
                'verbose_name': 'Diaries',
                'verbose_name_plural': 'Diaries',
                'db_table': 'Diaries',
            },
        ),
    ]
