# Generated by Django 3.1.5 on 2021-01-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='user_id'),
        ),
    ]
