# Generated by Django 3.1.5 on 2021-01-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210128_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='user_id'),
        ),
    ]
