# Generated by Django 3.1.5 on 2021-01-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=16, verbose_name='user_id')),
                ('username', models.CharField(max_length=16, verbose_name='user_name')),
                ('useremail', models.EmailField(max_length=128, verbose_name='user_email')),
                ('userphone', models.CharField(max_length=16, verbose_name='user_phone')),
                ('useraddress', models.CharField(max_length=128, verbose_name='user_address')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='register_time')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='modify_time')),
            ],
            options={
                'verbose_name': 'World_Users',
                'verbose_name_plural': 'World Users',
                'db_table': 'world_users',
            },
        ),
    ]
