# Generated by Django 3.1.5 on 2021-01-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='usergender',
            field=models.CharField(default='', max_length=2, null=True, verbose_name='user_name'),
        ),
        migrations.AddField(
            model_name='members',
            name='userpassword',
            field=models.CharField(default='', max_length=16, null=True, verbose_name='user_password'),
        ),
    ]
