# Generated by Django 3.1.5 on 2021-01-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210126_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='userpassword',
        ),
    ]
