# Generated by Django 3.1.5 on 2021-01-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_members_userpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='useraddress',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='user_address'),
        ),
    ]
