# Generated by Django 3.1.5 on 2021-01-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20210126_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='usergender',
            field=models.CharField(default='', max_length=2, null=True, verbose_name='user_gender'),
        ),
    ]
