# Generated by Django 3.1.5 on 2021-01-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20210126_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='username',
            field=models.CharField(max_length=16, null=True, verbose_name='user_name'),
        ),
    ]
